---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/rajugda1/mkchessacademy.com/
    
    # 1. Copy the Frontend Build (Contents of build to root)
    - /bin/cp -R -p build/* $DEPLOYPATH
    
    # 2. Copy the Backend API
    - /bin/mkdir -p $DEPLOYPATH/backend
    - /bin/cp -R -p backend/* $DEPLOYPATH/backend
    
    # 3. Safety check for .htaccess (Copy from build folder)
    - /bin/cp -p build/.htaccess $DEPLOYPATH/.htaccess